With the ispy2_mri qualifier for flowlayout import works. v0.0.3 So the entry point now works!
OTOH, running ispy2_mri.py directly, as in my shortcuts, now produces
PS C:\Users\rdboylan\Documents\ispy2_mri> $SOLO="C:\Users\rdboylan\AppData\Roaming\Python\Python310\site-packages\ispy2_mri\ispy2_mri.py"
PS C:\Users\rdboylan\Documents\ispy2_mri> py $SOLO
Traceback (most recent call last):
  File "C:\Users\rdboylan\AppData\Roaming\Python\Python310\site-packages\ispy2_mri\ispy2_mri.py", line 8, in <module>
    from ispy2_mri.flowlayout import FlowLayout
  File "C:\Users\rdboylan\AppData\Roaming\Python\Python310\site-packages\ispy2_mri\ispy2_mri.py", line 8, in <module>
    from ispy2_mri.flowlayout import FlowLayout
ModuleNotFoundError: No module named 'ispy2_mri.flowlayout'; 'ispy2_mri' is not a package

I strongly suspect a name clash between the module ispy2_mri and the python file
of the same name.